import type { Metadata } from "next";
import PagesLayout from "@/components/layouts/PagesLayout";
import "./globalStyles/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="#f5f5f5" />
        <meta name="robots" content="all" />
      </head>
      <PagesLayout>{children}</PagesLayout>
    </html>
  );
}
